### ISSUE TITLE
The function draw_LAF_matches() not defined

### ISSUE THREAD

**Issue by LozaKiN** [ucuapps/OpenGlue#2]
Hello,
First of all, thank you for sharing your work!
Unfortunately, when trying to use inference.py, the function draw_LAF_matches() doesn't seem to be defined anywhere.
Could you provide it please?

**Comment by ducha-aiki** [comment]
It is from kornia_moons. 
`pip install kirnia_moons`

**Comment by LozaKiN** [comment]
Woops you're right, thanks for your answer and sorry for the inconvenience
