### ISSUE TITLE
Typical Training Time

### ISSUE THREAD

**Issue by hit2sjtu** [ucuapps/OpenGlue#6]
Hi, nice work there. But I could not find any training time info in the repo or in the paper. Eg: OpenGlue w/ magic leap superpoint on X GPU for 1 epoch .etc. 
Will you kindly share more information so one can know everything is working as expected ?

**Comment by hit2sjtu** [comment]
Just as self note, I came across one BAD hard drive on new machine which make training extremely slow and difficult to debug. Glad the problem was finally solved.

**Comment by WallofWonder** [comment]
I'm training the model with SIFT feature cached, and it takes nearly 3 hours on 2 RTX3090 GPUs for 1 epoch.
I'm not sure if it is working properly.
So could you share some information about your training time on X GPU for 1 epoch?

**Comment by hit2sjtu** [comment]
Watch and check if your GPU is 100% utilized most of the time. If so, you are probably on the right way.
I did not use SIFT but with cached SuperPoint features, 1-2 hour per epoch is normal depends your card and batch size.

**Comment by WallofWonder** [comment]
> Watch and check if your GPU is 100% utilized most of the time. If so, you are probably on the right way. I did not use SIFT but with cached SuperPoint features, 1-2 hour per epoch is normal depends your card and batch size.

Thanks a lot.  I will also consider using SuperPoint features in the future
